package com.kev.tme.engine;

import com.kev.tme.model.OrderStatus;
import com.kev.tme.model.Trade;

import java.util.List;

/**
 * Result of submitting (or modifying) an order: the final status, how much was
 * filled and how much remains, and the trades generated by this submission.
 */
public class OrderResult {

    private final long orderId;
    private final OrderStatus status;
    private final long filledQuantity;
    private final long remainingQuantity;
    private final List<Trade> trades;

    public OrderResult(
            long orderId,
            OrderStatus status,
            long filledQuantity,
            long remainingQuantity,
            List<Trade> trades
    ) {
        this.orderId = orderId;
        this.status = status;
        this.filledQuantity = filledQuantity;
        this.remainingQuantity = remainingQuantity;
        this.trades = List.copyOf(trades);
    }

    public long getOrderId() {
        return orderId;
    }

    public OrderStatus getStatus() {
        return status;
    }

    public long getFilledQuantity() {
        return filledQuantity;
    }

    public long getRemainingQuantity() {
        return remainingQuantity;
    }

    public List<Trade> getTrades() {
        return trades;
    }
}
